# Generated by Django 4.1 on 2022-08-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assocapi', '0002_association_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
