# Generated by Django 4.1 on 2022-08-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assocapi', '0004_remove_association_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='is_association_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
