# Generated by Django 4.1 on 2022-08-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assocapi', '0006_alter_association_logoassociation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='Post/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assignee', models.ManyToManyField(related_name='name_association_post', to='Assocapi.association')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
